# Site settings. These are used to personalize your new site. If you look in the HTML files, you will see them accessed via {{ site.title }}, {{ site.email }}, and so on. You can create any custom variable you would like, and they will be accessible in the templates via {{ site.myvariable }}.
title: my Favorite
logo: /images/masthead.png
masthead_title: Sucias
email: gchingon@proton.me
description: >- # this means to ignore newlines until "baseurl:"
  "Gallo's Blog on random ish"
minimal_mistakes_skin: neon
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 7 # amount of posts to show
paginate_path: /page:num/
timezone: US/Central # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing. The following items will not be processed, by default. Create a custom list to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-redirect-from

author:
  name: "Sucias"
  avatar: "/images/author.png"
  bio: ""
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://sucias.xyz"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/gallo.salvaje.chingon"

footer:
  links:
    - label: "Instagram"
      icon: "fa-brands fa-instagram"
      url: "https://instagram.com/gallo.salvaje.chingon"
    - label: "TikTok"
      icon: "fa-brands fa-tiktok"
      url: "https://tiktok.com/@gallo.salvaje.chingon"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: false
      comments: false
      share: false
      related: false
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: false

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
